type token =
  | TokEof
  | TokLeftParen of (Lm_location.loc)
  | TokRightParen of (Lm_location.loc)
  | TokLeftBrack of (Lm_location.loc)
  | TokRightBrack of (Lm_location.loc)
  | TokPlus of (Lm_location.loc)
  | TokMinus of (Lm_location.loc)
  | TokStar of (Lm_location.loc)
  | TokSlash of (Lm_location.loc)
  | TokMod of (Lm_location.loc)
  | TokHat of (Lm_location.loc)
  | TokPipe of (Lm_location.loc)
  | TokAmp of (Lm_location.loc)
  | TokLsl of (Lm_location.loc)
  | TokLsr of (Lm_location.loc)
  | TokAsr of (Lm_location.loc)
  | TokAnd of (Lm_location.loc)
  | TokOr of (Lm_location.loc)
  | TokDot of (Lm_location.loc)
  | TokComma of (Lm_location.loc)
  | TokSemi of (Lm_location.loc)
  | TokLe of (Lm_location.loc)
  | TokLt of (Lm_location.loc)
  | TokEq of (Lm_location.loc)
  | TokNeq of (Lm_location.loc)
  | TokGt of (Lm_location.loc)
  | TokGe of (Lm_location.loc)
  | TokColonColon of (Lm_location.loc)
  | TokArrow of (Lm_location.loc)
  | TokId of (Lm_symbol.symbol * Lm_location.loc)
  | TokKey of (Lm_symbol.symbol * Lm_location.loc)
  | TokCatch of (Lm_location.loc)
  | TokInt of (int * Lm_location.loc)
  | TokFloat of (float * Lm_location.loc)
  | TokExp of (Omake_ast.exp)

val ast_exp :
  (Lexing.lexbuf  -> token) -> Lexing.lexbuf -> Omake_ast.exp
